name: ""
title: null

# navbar-col: ""
# navbar-text-col: ""
# navbar-border-col: ""
page-col: "#ECEFF4"
text-col: "#3B4252"
link-col: "#5E81AC"
# hover-col: ""
# footer-col: ""
# footer-text-col: ""
# footer-link-col: ""
# footer-hover-col: ""
